{% set name = "Fabric" %}
{% set version = "2.3.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "81572002a562b26df657ca10d06b5bcfc6fd56b53374037392c83d4a2158208f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - fab = fabric.main:main

requirements:
  host:
    - python <3
    - pip

  run:
    - python <3
    - paramiko >=1.10,<3.0

test:
  imports:
    - fabric
    - fabric.contrib

  commands:
    - fab --help

about:
  home: http://fabfile.org
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Fabric is a simple, Pythonic tool for remote execution and deployment.'
  dev_url: https://github.com/fabric/fabric/
  doc_url: http://docs.fabfile.org/

extra:
  recipe-maintainers:
    - pmlandwehr
