{% set name = "fabric" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfe960c1ae904e7624af9d40ad5b9b99581ed9c4fd09349c0d02b7486e1d0f89
  patches:
    - backport-2221.patch

build:
  number: 0
  noarch: python
  entry_points:
    - fab = fabric.main:program.run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - invoke >=2.0
    - paramiko >=2.4
    - python >=3.6

test:
  imports:
    - fabric
    - fabric.testing
  commands:
    - fab --help
    - pip check
  requires:
    - pip

about:
  home: http://fabfile.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fabric is a simple, Pythonic tool for remote execution and deployment.
  dev_url: https://github.com/fabric/fabric/
  doc_url: http://docs.fabfile.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - setu4993
    - ocefpaf
