{% set name = "Fabric" %}
{% set version = "1.14.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "81572002a562b26df657ca10d06b5bcfc6fd56b53374037392c83d4a2158208f" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [py3k]
  entry_points:
    - fab = fabric.main:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - paramiko >=1.10,<3.0

test:
  imports:
    - fabric
    - fabric.contrib

  commands:
    - fab --help

about:
  home: http://fabfile.org
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Fabric is a simple, Pythonic tool for remote execution and deployment.'
  description: |
    Fabric is a Python library and command-line tool for streamlining the use
    of SSH for application deployment or systems administration tasks.
  doc_url: http://docs.fabfile.org/
  doc_source_url: https://github.com/fabric/fabric/blob/master/sites/docs/index.rst#id1
  dev_url: https://github.com/fabric/fabric

extra:
  recipe-maintainers:
    - pmlandwehr
