{% set name = "fabric" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47f184b070272796fd2f9f0436799e18f2ccba4ee8ee587796fca192acd46cd2

build:
  number: 1
  noarch: python
  entry_points:
    - fab = fabric.main:program.run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - invoke >=1.3,<2.0
    - pathlib2
    - paramiko >=2.4
    - python

test:
  imports:
    - fabric
    - fabric.testing
  commands:
    - fab --help
    - pip check
  requires:
    - pip

about:
  home: http://fabfile.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fabric is a simple, Pythonic tool for remote execution and deployment.
  dev_url: https://github.com/fabric/fabric/
  doc_url: http://docs.fabfile.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - setu4993
