travis:
  secure:
    BINSTAR_TOKEN: qtQgAYaO/2JTRYedFWhFJ7M5pVd+XhPM3g1dHmlOcDoUwE+7NbAc4u/mPPVe5LtazlgsghswJJWFA8FdZnOblASHQznYwcj2tlhM1HmdPiC5gDdXa2aVRv76ADAXci4uBdt6Q8w3vMXwUC7yAJWDXcuzwOycedYG8pOEinf72JMyRJCrAVHesumiUnzpcxnTc4JOEj5bupbmSSoXSbsj8hIvmfzsN0rW9MKnOOQHmb1cjaee6wDnAGlHbsZA4kTraLz1zATdFbxA8tJ0oek8LxMKNGDHKLImS0e3VDC7LrL8DOzWlkoDe8frY/5S3YEJxFCodxBVaZe6BXUe5JeTHLYQMD75gXVM/xDd828IBKzziTUZtJtUxMvvFcHVD38KWihR80EwkQGzd1CFBHJkdLtfh6zAf9fFsHUT4/ar9jsT/zkuq0YzbIpTgV1zVSSK18HcB/6qP3Eew485IUFGzVpM0h1W1aZmCvXabLhFLddEEAmWrEvTYllXp/yp00OqdCu2E+hz0OHxrjoqHFXmQ70p2X9I1iQCbtjCrAdMKKylLSUKsaPLXx5wDlItW0vCNRnDGeZjCVAtWQNL7Fp2H4bHKvYXyDUWj3HEWBgeN5EGr1lHFZ266UTOALpA793NIh3FrDm3C9+LGBsZCJCvGlO+XQB8T814IzYb2R1HwvM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
